
import { createClient } from '@supabase/supabase-js';
import { Infographic } from './types'; // Assuming your Infographic type is defined here

// ===================================================================================
// Using your provided Supabase credentials directly for local development.
// ===================================================================================

const supabaseUrl = 'https://dldiedktrkbwpqznxdwk.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZGllZGt0cmtid3Bxem54ZHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTM4ODMsImV4cCI6MjA2NDE2OTg4M30.teFTNA7Zez_qUO9-wQALPdw_ULLmmfNhOlNHD_CdtHc';

if (!supabaseUrl) {
  throw new Error(
    `Supabase URL is missing. This should not happen with hardcoded values.`
  );
}

if (!supabaseAnonKey) {
  throw new Error(
    `Supabase Anon Key is missing. This should not happen with hardcoded values.`
  );
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);

// Define a type for your database schema. This helps with TypeScript type safety.
// This should align with the table created in your Supabase project.
export interface Database {
  public: {
    Tables: {
      infographics: {
        Row: Infographic; // The type of data returned from the table (includes id, created_at)
        Insert: Omit<Infographic, 'id' | 'created_at'>; // The type of data to insert (id and created_at are auto-generated by Supabase)
                                                        // 'date' is client-generated and part of the insert
        Update: Partial<Omit<Infographic, 'id' | 'created_at'>>; // The type of data to update
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
  };
}
