
export enum DisplayCategory {
  INFOGRAPHIC = 'Infographic', // Changed from GENERAL
  ARTICLE = 'บทความ',
  TECHNOLOGY = 'เทคโนโลยี',
}

export interface Infographic {
  id: string; // Supabase will generate a UUID, which is a string
  title: string; // หัวข้อ
  imageUrl: string; // url รูป
  content: string; // เรื่อง/เนื้อหา (main detailed content)
  summary: string; // Short summary for cards
  displayCategory: DisplayCategory; // Category for page placement
  tags: string[]; // Sub-categories/keywords for filtering e.g., พืชไร่, พืชสวน
  date: string; // Formatted date string generated by client
  created_at?: string; // Auto-generated by Supabase (TIMESTAMPTZ)
}

export const ALL_TAGS_OPTION = 'ทั้งหมด';